In [5]:
import tensorflow as tf
import pandas as pd
from numpy import *
import numpy as np

In [9]:
node1=tf.constant(3,tf.float32)
node2=tf.constant(7)

In [5]:
print(node1)
print(node2)

Tensor("Const_2:0", shape=(), dtype=float32)
Tensor("Const_3:0", shape=(), dtype=int32)


In [10]:
sess=tf.Session()
sess.run(node1)
sess.run(node2)

7

In [ ]:
#Additon
node3=tf.add(node1,node2)
#not possible as both aere of diff data types


In [12]:
node1=tf.constant(3)
node2=tf.constant(7)

In [13]:
node3=tf.add(node1,node2) #node1+node2 will also work

In [14]:
sess.run(node3)

10

In [15]:
##A graph can be parameterized to accept external inputs, known as placeholders.
#A placeholder is a promise to provide a value later.
a=tf.placeholder(tf.int32)
b=tf.placeholder(tf.int32)

In [16]:
add=a+b

In [18]:
sess.run(add,{a:3,b:5})

8

In [21]:
sess.run(add*3,{a:3,b:5})

24

In [22]:
#Variables allow us to add trainable parameters to a graph. They are constructed with a type and initial value:
W = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
x=tf.placeholder(tf.float32)
linear_model=W*x+b

In [23]:
#variables must be intialized in order to use it
init = tf.global_variables_initializer()
sess.run(init)#this is for intilization

In [24]:
#
print(sess.run(linear_model, {x:[1,2,3,4]}))

[ 0.          0.30000001  0.60000002  0.90000004]


In [25]:
y = tf.placeholder(tf.float32)

In [28]:
squared_deltas = tf.square(linear_model - y)
loss = tf.reduce_sum(squared_deltas)
print(sess.run(loss, {x:[1,2,3,4], y:[0,-1,-2,-3]}))

23.66


In [29]:
fixW = tf.assign(W, [-1.])
fixb = tf.assign(b, [1.])
sess.run([fixW, fixb])
print(sess.run(loss, {x:[1,2,3,4], y:[0,-1,-2,-3]}))

0.0


In [3]:
df=pd.read_csv('data.csv',sep=',',header=None)

In [4]:
df.head(10)

0          1
0  32.502345  31.707006
1  53.426804  68.777596
2  61.530358  62.562382
3  47.475640  71.546632
4  59.813208  87.230925
5  55.142188  78.211518
6  52.211797  79.641973
7  39.299567  59.171489
8  48.105042  75.331242
9  52.550014  71.300880

In [7]:
points=genfromtxt('data.csv',delimiter=',')

In [18]:
len(points)
points[:,0]

array([ 32.50234527,  53.42680403,  61.53035803,  47.47563963,
        59.81320787,  55.14218841,  52.21179669,  39.29956669,
        48.10504169,  52.55001444,  45.41973014,  54.35163488,
        44.1640495 ,  58.16847072,  56.72720806,  48.95588857,
        44.68719623,  60.29732685,  45.61864377,  38.81681754,
        66.18981661,  65.41605175,  47.48120861,  41.57564262,
        51.84518691,  59.37082201,  57.31000344,  63.61556125,
        46.73761941,  50.55676015,  52.22399609,  35.56783005,
        42.43647694,  58.16454011,  57.50444762,  45.44053073,
        61.89622268,  33.09383174,  36.43600951,  37.67565486,
        44.55560838,  43.31828263,  50.07314563,  43.87061265,
        62.99748075,  32.66904376,  40.16689901,  53.57507753,
        33.86421497,  64.70713867,  38.11982403,  44.50253806,
        40.59953838,  41.72067636,  51.08863468,  55.0780959 ,
        41.37772653,  62.49469743,  49.20388754,  41.10268519,
        41.18201611,  50.18638949,  52.37844622,  50.13

# Divided our data into training and test set

In [22]:
x_train=points[0:80,0]
y_train=points[0:80,1]
x_eval=points[80:100,0]
y_eval=points[80:100,1]

In [23]:
len(x_train)

80

In [21]:
x_train

array([ 32.50234527,  53.42680403,  61.53035803,  47.47563963,
        59.81320787,  55.14218841,  52.21179669,  39.29956669,
        48.10504169,  52.55001444,  45.41973014,  54.35163488,
        44.1640495 ,  58.16847072,  56.72720806,  48.95588857,
        44.68719623,  60.29732685,  45.61864377,  38.81681754,
        66.18981661,  65.41605175,  47.48120861,  41.57564262,
        51.84518691,  59.37082201,  57.31000344,  63.61556125,
        46.73761941,  50.55676015,  52.22399609,  35.56783005,
        42.43647694,  58.16454011,  57.50444762,  45.44053073,
        61.89622268,  33.09383174,  36.43600951,  37.67565486,
        44.55560838,  43.31828263,  50.07314563,  43.87061265,
        62.99748075,  32.66904376,  40.16689901,  53.57507753,
        33.86421497,  64.70713867,  38.11982403,  44.50253806,
        40.59953838,  41.72067636,  51.08863468,  55.0780959 ,
        41.37772653,  62.49469743,  49.20388754,  41.10268519,
        41.18201611,  50.18638949,  52.37844622,  50.13

### Step 1

In [ ]:
 
features = [tf.contrib.layers.real_valued_column("x", dimension=1)]

### Step 2

In [25]:

#simlar to sklearn importing the required Algorithm to use
#Give the input of your feature columns
estimator = tf.contrib.learn.LinearRegressor(feature_columns=features)


INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x117b82668>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': None}


### Step3

In [26]:

#Give your Data
##This is also similar to sklearn
input_fn = tf.contrib.learn.io.numpy_input_fn({"x":x_train}, y_train,
                                              batch_size=4,
                                              num_epochs=1000)

In [27]:
#Evaluating the test 
eval_input_fn = tf.contrib.learn.io.numpy_input_fn(
    {"x":x_eval}, y_eval, batch_size=4, num_epochs=1000)

### step 4 :No fo Training Steps

In [28]:
#step4 :No fo Training Steps
estimator.fit(input_fn=input_fn, steps=1000)


Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/_3/ck8mb1qn35dg_y8z655dyx358dk92j/T/tmp29ju7prb/model.ckpt.
INFO:tensorflow:loss = 4725.19, step = 1
INFO:tensorflow:global_step/sec: 1439.37
INFO:tensorflow:loss = 98.1073, step = 101 (0.071 sec)
INFO:tensorflow:global_step/sec: 1422.59
INFO:tensorflow:loss = 72.7025, step = 201 (0.070 sec)
INFO:tensorflow:global_step/sec: 1461.97
INFO:tensorflow:loss = 147.472, step = 301 (0.068 sec)
INFO:tensorflow:global_step/sec: 1418.36
INFO:tensorflow:loss = 56.2735, step = 401 (0.070 sec)
INFO:tensorflow:global_step/sec: 1429.58
INFO:tensorflow:loss = 98.7253, step = 501

LinearRegressor(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._RegressionHead object at 0x117acceb8>, 'feature_columns': [_RealValuedColumn(column_name='x', dimension=1, default_value=None, dtype=tf.float32, normalizer=None)], 'optimizer': None, 'gradient_clip_norm': None, 'joint_weights': False})

### Step 5 Calculating the Losses

In [29]:
# Here we evaluate how well our model did.
train_loss = estimator.evaluate(input_fn=input_fn)
eval_loss = estimator.evaluate(input_fn=eval_input_fn)
print("train loss: %r"% train_loss)
print("eval loss: %r"% eval_loss)

Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-06-25-13:38:10
INFO:tensorflow:Restoring parameters from /var/folders/_3/ck8mb1qn35dg_y8z655dyx358dk92j/T/tmp29ju7prb/model.ckpt-1000
INFO:tensorflow:Finished evaluation at 2017-06-25-13:38:19
INFO:tensorflow:Saving dict for global step 1000: global_step = 1000, loss = 115.093
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Star